### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by TheChuckster** [cyberguijarro/minibson#3]
Would you ever consider relicensing this under a more dev-friendly and more free license such as Apache or MIT?

Right now, to my understanding (IANAL, etc.), anybody who wants to use this library has to (re-)license their code as GPL.

**Comment by cyberguijarro** [comment]
Sorry for the delayed answer. I try to release these small developments as GPL, as a way of giving back everything I've taken from the open source community.

What are your exact needs?

**Comment by TheChuckster** [comment]
Just need something that is non-infectious, as I am working on a commercial project for a client that could really benefit from bson, but said client _definitely_ does not want their entire project licensed as GPL (per the GPL license), as the result of me using one GPL library.

Hope you can help us by relaxing the license to something that still gives back to the community, but is not infectious, like Apache or MIT. Even LGPL would be better for a library (the vast majority of OSS libraries use LGPL instead of GPL, for that very reason).

Thanks!

**Comment by cyberguijarro** [comment]
Done.

**Comment by cyberguijarro** [comment]
Also, thanks a lot for considering minibson for you project!
