### ISSUE TITLE
Is the +1u for string types correct?

### ISSUE THREAD

**Issue by TomHarte** [cyberguijarro/minibson#8]
i.e. this one: https://github.com/cyberguijarro/minibson/blob/82bc160b824ade110171f7410fd433df8df94060/microbson.hpp#L97

There's an extra byte for binary blobs, to identify the subtype, but I don't think strings have one as, to quote the spec: "String - The int32 is the number bytes in the (byte*) + 1 (for the trailing '\x00').", i.e. the complete length of the string data is included in the 4-byte value. No extra bytes.

**Comment by cyberguijarro** [comment]
Hi Thomas,

According to the BSON spec, “binary” entries don’t have a null terminator, but do have a “subtype” 1-byte field. I believe the “+1” in the binary case accounts for that:

string	::=	int32 (byte*) "\x00"
binary	::=	int32 subtype (byte*)

Best regards,
Emilio.

**Comment by TomHarte** [comment]
Yes — think the +1u is correct for binary types, but incorrect for string types. microbson uses the same logic for both.

**Comment by TomHarte** [comment]
Oh, actually I can see that #6 appears to say the same thing. So I'll let you review that, and close this — you definitely don't need to know about this twice.

**Comment by cyberguijarro** [comment]
Now I see what you mean, I just fixed it by merging #6.

Thanks!
